/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-smart_meters
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_SMART_METERS_API_H
#define INCLUDED_SMART_METERS_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_smart_meters_EXPORTS
#define SMART_METERS_API __GR_ATTR_EXPORT
#else
#define SMART_METERS_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_SMART_METERS_API_H */
